name: Build Linux App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to v4

      - name: Install Linux Build Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Linux Release
        run: flutter build linux --release

      - name: Upload Finished App
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: AeroDrop-Linux
          path: build/linux/x64/release/bundle/
